export const FILTERS = ['All', 'Mammals', 'Birds', 'Reptiles', 'Fish', 'Amphibians']

export const ANIMALS = [
  {
    id: 1,
    name: 'Snow Leopard',
    category: 'Mammals',
    habitat: 'Arctic',
    status: 'Vulnerable',
    description: 'A solitary big cat adapted to the cold mountain ranges of Central Asia, known for its thick pale-grey coat.',
    image: 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=600&q=80',
  },
  {
    id: 2,
    name: 'Great White Shark',
    category: 'Fish',
    habitat: 'Ocean',
    status: 'Vulnerable',
    description: 'The ocean\'s apex predator, capable of detecting a single drop of blood from miles away.',
    image: 'https://images.unsplash.com/photo-1504595403659-9088ce801e29?w=600&q=80',
  },
  {
    id: 3,
    name: 'African Elephant',
    category: 'Mammals',
    habitat: 'Savanna',
    status: 'Endangered',
    description: 'Earth\'s largest land animal, with complex social bonds and extraordinary memory.',
    image: 'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80',
  },
  {
    id: 4,
    name: 'Harpy Eagle',
    category: 'Birds',
    habitat: 'Jungle',
    status: 'Vulnerable',
    description: 'One of the world\'s largest and most powerful eagles, hunting prey through dense rainforest canopy.',
    image: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=600&q=80',
  },
  {
    id: 5,
    name: 'Green Sea Turtle',
    category: 'Reptiles',
    habitat: 'Ocean',
    status: 'Endangered',
    description: 'An ancient reptile that navigates thousands of miles across open ocean to return to its birth beach.',
    image: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=600&q=80',
  },
  {
    id: 6,
    name: 'Bengal Tiger',
    category: 'Mammals',
    habitat: 'Forest',
    status: 'Endangered',
    description: 'The largest wild cat species, a powerful swimmer and nocturnal hunter of South Asian forests.',
    image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=600&q=80',
  },
  {
    id: 7,
    name: 'Poison Dart Frog',
    category: 'Amphibians',
    habitat: 'Jungle',
    status: 'Least Concern',
    description: 'Tiny yet lethal, these vibrant frogs advertise their toxicity through vivid warning colours.',
    image: 'https://images.unsplash.com/photo-1496112576525-8b31e9ce5b0e?w=600&q=80',
  },
  {
    id: 8,
    name: 'Komodo Dragon',
    category: 'Reptiles',
    habitat: 'Desert',
    status: 'Endangered',
    description: 'The world\'s largest living lizard, a stealthy ambush predator with venomous saliva.',
    image: 'https://images.unsplash.com/photo-1605565348518-bef3e7d6fed8?w=600&q=80',
  },
  {
    id: 9,
    name: 'Humpback Whale',
    category: 'Mammals',
    habitat: 'Ocean',
    status: 'Least Concern',
    description: 'Known for their haunting songs and spectacular breaching displays across all the world\'s oceans.',
    image: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=600&q=80',
  },
]